name: CI
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up kubectl
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.DIGITAL_OCEAN }}
          clusterName: spacedoglabs

      - name: Get nodes
        run: kubectl get nodes

      - name: Write the Thing
        continue-on-error: true
        run: exit 1 | echo container_exists=$? >> $GITHUB_ENV

      - name: Read the Thing
        run: echo ${{ env.container_exists }}

      - name: Read the Thing
        run: |
          if echo ${{ env.container_exists  == '1' }} | grep -c "true"
          then
            echo "Run this?"
          else
            echo "Skipped!"
          fi
