name: CI
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up kubectl
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.DIGITAL_OCEAN }}
          clusterName: spacedoglabs

      - name: Get nodes
        run: kubectl get nodes

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 6000

      - name: Check if Version Already Exists in Container Registry
        id: version-exists
        continue-on-error: true
        run: docker manifest inspect registry.digitalocean.com/spacedoglabs/backends:bout-heck > /dev/null || echo "container_exists=$?" >> $GITHUB_ENV

      - name: Read the Thing
        run: echo ${{ env.container_exists }}

      - name: Read the Thing
        run: |
          if echo ${{ env.container_exists  == '1' }} | grep -c "true"
          then
            echo "Build and push it! It doesn't exists."
          else
            echo "Skipped! Container exists."
          fi
